# Eliminar elementos en Series y DataFrame

In [ ]:
Veamos como eliminar elementos en Series y Data frame

In [1]:
# importamos los modulos
import pandas as pd
import numpy as np

In [2]:
# creamos una Series, apartir de arrays
np.arange(3)

array([0, 1, 2])

In [4]:
# crear serie
serie1 = pd.Series(np.arange(4), index = ['a', 'b', 'c', 'd'])
serie1

a    0
b    1
c    2
d    3
dtype: int32

In [6]:
# Borrar elemento en Serie

# si quiero eliminar el elemento de c, 2
serie1.drop('c')

a    0
b    1
d    3
dtype: int32

In [ ]:
# Borrar elementos en DataFrame


In [8]:
# primero creamos arrays
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# guardamos con nombre
lis_valores = np.arange(9).reshape(3,3)
lis_valores

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
lis_indices = ['a', 'b', 'c']
lis_indices

['a', 'b', 'c']

In [11]:
lis_columnas = ['c1', 'c2', 'c3']
lis_columnas

['c1', 'c2', 'c3']

In [15]:
# creamos un DF apartir de los arrays creados anteriormente
DF1 = pd.DataFrame(lis_valores, index = lis_indices, columns = lis_columnas)
DF1

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [16]:
# Ahora, quiero eliminar la fila b, para ello usamos .drop y dentro el indice a eliminar, en este caso b.
DF1.drop('b')

c1  c2  c3
a   0   1   2
c   6   7   8

In [18]:
# Para eliminar columnas, usamos un parametro adicional llamdo axis = 1, 1 es por columna
DF1.drop('c2', axis = 1)

c1  c3
a   0   2
b   3   5
c   6   8